### ISSUE TITLE
Error chaincode is being launched

### ISSUE THREAD

**Issue by ki0apa** [hyperledger/composer#1670]
I've sent around 500 REST requests to a network and several errors occur.

## Context

I set up a basic network using the tutorial found here: [Developer Guide](https://hyperledger.github.io/composer/tutorials/developer-guide.html). I then made a REST server and spammed it with requests. These requests either created a new asset or participant or submitted a transaction. After submitting about 500 requests, the network seems to crash and several errors are given. If I followed the steps on the website correctly, this should not be occurring. I am not sure if it is an error with the website instructions or composer itself.

## Expected Behavior
I should be able to post many requests without any errors.

## Actual Behavior

I'm getting some of the following errors. 

`Unhandled error for request POST /api/org.example.mynetwork.Trader: Error: error trying to query chaincode. Error: Error executing chaincode: Failed to execute transaction (Timeout expired while executing transaction) at channel.queryByChaincode.then.catch (/home/ubuntu/composer/my-network/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:758:34)`

`Unhandled error for request POST /api/org.example.mynetwork.Commodity: Error: error trying to query chaincode. Error: Error executing chaincode: premature execution - chaincode (my-network:0.9.2) is being launched at channel.queryByChaincode.then.catch (/home/ubuntu/composer/my-network/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:758:34)`

In the peer docker logs, the first error reported is:

` [chaincode] processStream -> ERRO 69f63[0m Error handling chaincode support stream: rpc error: code = Canceled desc = context canceled`

## Steps to Reproduce
1. Download the basic sample network using the link provided in the context section on an aws instance (Ubuntu 16.04, t2.xlarge, Ohio)
2. Set up a rest server on the aws instance.
3. Send up to 500 requests to the server.

## Existing issues

- [x] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

- [Timeout Error](https://github.com/hyperledger/composer/issues/1514) 
- I asked this question on rocket chat and stack overflow and got no sufficient response.

## Context
I'm trying to test the scalability of Hyperledger Composer.

## Your Environment

Docker version 17.06.0-ce, build 02c1d87
docker-compose version 1.13.0, build 1719ceb
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
composer-cli                   v0.10.0
composer-admin                 v0.10.0
composer-client                v0.10.0
composer-common                v0.10.0
composer-runtime-hlf           v0.10.0
composer-runtime-hlfv1         v0.10.0
npm-version: 5.3.0
node version: 6.11.1

The rest server is running on an aws instance and I am sending requests on a local computer with fedora 25.

**Comment by davidkel** [comment]
@ki0apa Thanks for the Peer logs. It looks like the chaincode container for some reason terminates. Fabric on the next request notices this and brings up another chaincode container and isn't ready to accept requests. Unfortunately the chaincode logs you attached are for the newly spawned container and so don't provide any insight into why the chaincode container terminated. Could you add the following environment variable to your Peer definition and restart your Peer (or fabric) and run the test again. This will put the chaincode container logs into the Peer logs so will hopefully capture information from the failing chaincode container.
`CORE_VM_DOCKER_ATTACHSTDOUT=true`

So for example if you use docker-compose to bring up the environment then your peer definition might start with something like
```
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:x86_64-1.0.0
    environment:
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=composer_default
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start --peer-defaultchain=false
```
